name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar un script
      - uses: actions/checkout@v2
        run: echo "Hello, World!"